---
title: "Analysis Result"
author: "Rodrigo Calvo Rubio"
output: html_document
self_contained: no
---
```{r}
# install.packages("tidyverse")
# install.packages("htmlwidgets")
# install.packages("plotly")
# install.packages("ggplot2")
# install.packages("png")
print(.libPaths())
```
```{r Import-Libraries}
# .libPaths('D:/R-4.1.1/library')
# .library('/Library/Frameworks/R.framework/Versions/4.1/Resources/library')

library(tidyverse)
library(ggplot2)
library(plotly)
library(htmlwidgets)
library(png)

```
# Reading user data CSV
```{r Get-Data-From-CSV}
data <- read.csv(file = './dataset.csv', stringsAsFactors = FALSE)
```
# Example sorting data by user ID code -> chanfe decreasing to check results
```{r Sort-Data-And-Save-CSV}
dataFinal <- data[order(data[, "CODE"]), , drop = FALSE]
df <- data.frame(dataFinal)
write.csv(df, file = '../tmp/result.csv')
```
# Writing user data in final CSV
# Loop over the messages sent in different exercises
```{r Messages-plot}
messages <- df %>%
        select(matches('MESSAGES[1-9].[1-9]$'))

exercise <- ''
for (i in seq_along(messages)) {
        exerciseName <- gsub("\\.","-",names(messages)[i])
        print(paste(exerciseName, messages[i]))
        exercise <-c(df[names(messages)[i]])
        value <- unlist(exercise[1], use.names=FALSE)
        file <- paste(exerciseName,".png", sep="")
        ggplot(data=df, aes(x=as.factor(df$CODE), y=value)) +
         geom_bar(stat="identity")
        ggsave(paste("./plots/analysis_",file, sep=""))
        # ggplot(data=df, aes(x=as.factor(df$CODE), y=value)) +
        #  geom_bar(stat="identity")
        # ggsave(paste("./plots/messages/analysis_",file, sep=""))
}

```
```{r Rights-Plot}
rights <- df %>%
        select(matches('RIGHTS[1-9].[1-9]$'))

exercise <- ''
for (i in seq_along(rights)) {
        exerciseName <- gsub("\\.","-",names(rights)[i])
        print(paste(exerciseName, rights[i]))
        exercise <-c(df[names(rights)[i]])
        value <- unlist(exercise[1], use.names=FALSE)
        file <- paste(exerciseName,".png", sep="")
        ggplot(data=df, aes(x=as.factor(df$CODE), y=value)) +
                geom_bar(stat="identity")
        ggsave(paste("./plots/analysis_",file, sep=""))
}
```
```{r Deletions-Plot}
deletions <- df %>%
        select(matches('DELETIONS[1-9].[1-9]$'))

exercise <- ''
for (i in seq_along(deletions)) {
        exerciseName <- gsub("\\.","-",names(deletions)[i])
        print(paste(exerciseName, deletions[i]))
        exercise <-c(df[names(deletions)[i]])
        value <- unlist(exercise[1], use.names=FALSE)
        file <- paste(exerciseName,".png", sep="")
        ggplot(data=df, aes(x=as.factor(df$CODE), y=value)) +
                geom_bar(stat="identity")
        ggsave(paste("./plots/analysis_",file, sep=""))
}
```
```{r Inputs-Plot}
inputs <- df %>%
        select(matches('INPUTS[1-9].[1-9]$'))

exercise <- ''
for (i in seq_along(inputs)) {
        exerciseName <- gsub("\\.","-",names(inputs)[i])
        print(paste(exerciseName, inputs[i]))
        exercise <-c(df[names(inputs)[i]])
        value <- unlist(exercise[1], use.names=FALSE)
        file <- paste(exerciseName,".png", sep="")
        ggplot(data=df, aes(x=as.factor(df$CODE), y=value)) +
                geom_bar(stat="identity")
        ggsave(paste("./plots/analysis_",file, sep=""))
}
```
```{r Wrongs-Plot}
wrongs <- df %>%
        select(matches('WRONGS[1-9].[1-9]$'))

exercise <- ''
for (i in seq_along(wrongs)) {
        exerciseName <- gsub("\\.","-",names(wrongs)[i])
        print(paste(exerciseName, wrongs[i]))
        exercise <-c(df[names(wrongs)[i]])
        value <- unlist(exercise[1], use.names=FALSE)
        file <- paste(exerciseName,".png", sep="")
        ggplot(data=df, aes(x=as.factor(df$CODE), y=value)) +
                geom_bar(stat="identity")
        ggsave(paste("./plots/analysis_",file, sep=""))
}
```
